version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${TAG}
    environment: ['http.host=0.0.0.0', 'transport.host=127.0.0.1']
    ports: ['127.0.0.1:9201:9200']
    networks: ['stack']
    volumes:
      - data-volume:/usr/share/elasticsearch/data
networks: {stack: {}}
volumes:
  data-volume: